language: node_js
node_js:
  - "5"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install
services: mongodb
cache:
  directories:
    - node_modules
script:
  - npm install
  - npm install mysql
  - node server/bootstrap.js